### ISSUE TITLE
Unable to process own corpus

### ISSUE THREAD

**Issue by efiltz** [Lambda-3/IndraIndexer#2]
Hi,
i'd like to create an index for my own domain-specific corpus for using it with Indra. 
I downloaded the IndraIndexer and tried to compile it, however there are missing dependencies. 
`Failed to execute goal on project indra-preprocessing: Could not resolve dependencies for project org.lambda3.indra:indra-preprocessing:jar:1.1.0-rc4: Could not find artifact org.lambda3.indra:indra-essentials:jar:2.2.0-rc7 in central`

Can you please tell me how to process my own corpus?
Thank you!

**Comment by julsal** [comment]
Hi @efiltz, thanks for your interest in IndraIndexer. Those modules are available in the main Indra project. Please, install this version here: https://github.com/Lambda-3/Indra/releases/tag/2.2.0-rc7

**Comment by efiltz** [comment]
@julsal Thank you very much, that solved the problem!
